=== ashishpavan/front-and-backend-web/cd.dtd
<!ELEMENT cd (album+)>
<!ELEMENT album (singer,production,name,type)>
<!ELEMENT singer (#PCDATA)>
<!ELEMENT production (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>

=== ashishpavan/front-and-backend-web/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd SYSTEM "cd.dtd">
<cd>
<album>
    <singer>Taylor Swift</singer>
    <production>Taylor Swift</production>
    <name>Blank Space</name>
    <type>Love</type>
</album>
<album>
    <singer>Ed Sheeran</singer>
    <production>Ed Sheeran</production>
    <name>Perfect</name>
    <type>Love</type>
</album>
<album>
    <singer>John Cooper</singer>
    <production>Skillet</production>
    <name>Legendary</name>
    <type>Rock</type>
</album>
</cd>
